# Generated by Django 3.0.3 on 2020-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0004_auto_20200513_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='content',
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='origin/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='request',
            name='result_image',
            field=models.ImageField(default=None, null=True, upload_to='mask/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
