# Generated by Django 3.0.3 on 2020-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0006_auto_20200513_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='result_image',
            field=models.ImageField(blank=True, default=None, upload_to='mask/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
