# Generated by Django 3.0.3 on 2020-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('SB', 'Stand-by'), ('PR', 'Processing'), ('FN', 'Finish'), ('ER', 'Error'), ('DU', 'Deleted by User'), ('EX', 'Expired')], default='SB', max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='mod_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
