# Generated by Django 3.0.3 on 2020-05-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0007_auto_20200513_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Post',
        ),
    ]
