# Generated by Django 3.0.3 on 2020-05-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0008_auto_20200513_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
